## 3-DOF Manipulator Design Calculator - Forward Kinematics

In [1]:
import numpy as np
import math


In [2]:
##FORWARD KINEMATICS

In [3]:
a1 = float (input("a1 = " )) # a1 = 40
a2 = float (input("a2 = " )) # a2 = 50
a3 = float (input("a3 = " )) # a3 = 30
a4 = float (input("a4 = " )) # a4 = 60
a5 = float (input("a5 = " )) # a5 = 40

T1 = float (input("T1 = " )) # T1 = 0
T2 = float (input("T2 = " )) # T2 = 0
d3 = float (input("d3 = " )) # d3 = 100

T1 = (T1/180.0)*np.pi # Theta 1 in radians
T2 = (T2/180.0)*np.pi # Theta 2 in radians

PT = [[T1,(0.0/180.0)*np.pi,a2,a1],
    [T2,(180.0/180.0)*np.pi,a4,a3],
    [(0.0/180.0)*np.pi,(0.0/180.0)*np.pi,0,a5+d3]]

i = 0
H0_1 = [[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),PT[i][3]],
        [0,0,0,1]]

i = 1
H1_2 = [[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),PT[i][3]],
        [0,0,0,1]]

i = 2
H2_3 = [[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),PT[i][3]],
        [0,0,0,1]]

H0_1 = np.matrix(H0_1)
print("H0_1=")
print (H0_1)

H1_2 = np.matrix(H1_2)
print("H1_2=")
print (H1_2)

H2_3 = np.matrix(H2_3)
print("H2_3=")
print (H2_3)

H0_2 = np.dot (H0_1,H1_2)
H0_3 = np.dot (H0_2,H2_3)
print("H0_3=")
print(np.matrix(H0_3))


H0_1=
[[ 1. -0.  0. 50.]
 [ 0.  1. -0.  0.]
 [ 0.  0.  1. 40.]
 [ 0.  0.  0.  1.]]
H1_2=
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  6.0000000e+01]
 [ 0.0000000e+00 -1.0000000e+00 -1.2246468e-16  0.0000000e+00]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00  3.0000000e+01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
H2_3=
[[  1.  -0.   0.   0.]
 [  0.   1.  -0.   0.]
 [  0.   0.   1. 140.]
 [  0.   0.   0.   1.]]
H0_3=
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  1.10000000e+02]
 [ 0.00000000e+00 -1.00000000e+00 -1.22464680e-16 -1.71450552e-14]
 [ 0.00000000e+00  1.22464680e-16 -1.00000000e+00 -7.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [4]:
H0_2 = np.dot (H0_1,H1_2)
print("H0_2=")
print(np.matrix(H0_2))


H0_2=
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.1000000e+02]
 [ 0.0000000e+00 -1.0000000e+00 -1.2246468e-16  0.0000000e+00]
 [ 0.0000000e+00  1.2246468e-16 -1.0000000e+00  7.0000000e+01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


## POSITION VECTOR

In [5]:
X0_3 = H0_3[0,3]
print("X = ", X0_3)
Y0_3 = H0_3[1,3]
print("Y = ", Y0_3)
Z0_3 = H0_3[2,3]
print("Z = ", Z0_3)



X =  110.0
Y =  -1.7145055188062946e-14
Z =  -70.0


### Jacobian Matrix

### 1. Linear/Prismatic Vector

In [6]:
# Row 1 - 3, Column 1

J1a = [[1,0,0],[0,1,0],[0,0,1]]
Z_1 = [[0],[0],[1]] # the [0,0,1] vector

J1a = np.dot(J1a,Z_1)
print("J1a = ")
print(np.matrix(J1a))

J1b_1 = H0_3[0:3, 3:]
J1b_1 = np.matrix(J1b_1)
#print(J1b_1)

J1b_2 = [0]
J1b_2 = np.matrix(J1b_2)
#print(J1b_2)

J1b = J1b_1 - J1b_2
print("J1b = ")
print(J1b)

J1 = [[(J1a[1,0]*J1b[2,0])-(J1a[2,0]*J1b[1,0])],
[(J1a[2,0]*J1b[0,0])-(J1a[0,0]*J1b[2,0])],
[(J1a[0,0]*J1b[1,0])-(J1a[1,0]*J1b[0,0])]]
print("J1 = ")
print (np.matrix(J1))



J1a = 
[[0]
 [0]
 [1]]
J1b = 
[[ 1.10000000e+02]
 [-1.71450552e-14]
 [-7.00000000e+01]]
J1 = 
[[ 1.71450552e-14]
 [ 1.10000000e+02]
 [-0.00000000e+00]]


In [7]:
# Row 1 -3, Column 2

J2a = H0_1 [0:3,0:3]
J2a = np.dot(J2a,Z_1)
print("J2a = ")
print(J2a)

J2b_1 = H0_3[0:3, 3:]
J2b_1 = np.matrix(J2b_1)
#print(J2b_1)

J2b_2 = H0_1[0:3, 3:]
J2b_2 = np.matrix(J2b_2)
#print(J2b_2)

J2b = J2b_1 - J2b_2
print("J2b = ")
print(J2b)

J2 = [[(J2a[1,0]*J2b[2,0])-(J2a[2,0]*J2b[1,0])],
[(J2a[2,0]*J2b[0,0])-(J2a[0,0]*J2b[2,0])],
[(J2a[0,0]*J2b[1,0])-(J2a[1,0]*J2b[0,0])]]
print("J2 = ")
print (np.matrix(J2))

J2a = 
[[0.]
 [0.]
 [1.]]
J2b = 
[[ 6.00000000e+01]
 [-1.71450552e-14]
 [-1.10000000e+02]]
J2 = 
[[ 1.71450552e-14]
 [ 6.00000000e+01]
 [-0.00000000e+00]]


In [8]:
## Row 1 - 3, Column 3

J3 = H0_2[0:3,0:3]
J3 = np.dot(J3,Z_1)
print('J3 = ')
print(np.matrix(J3))


J3 = 
[[ 0.0000000e+00]
 [-1.2246468e-16]
 [-1.0000000e+00]]


### 2.Rotation/Orientation Vector

In [9]:
J4 = [[1,0,0],[0,1,0],[0,0,1]]
J4 = np.dot(J4,Z_1)
print("J4 = ")
print(np.matrix(J4))

J5 = H0_1 [0:3,0:3]
J5 = np.dot(J5,Z_1)
print("J5 = ")
print(J5)

J6 = [[0],[0],[0]]
print("J6 = ")
print(np.matrix(J6))


J4 = 
[[0]
 [0]
 [1]]
J5 = 
[[0.]
 [0.]
 [1.]]
J6 = 
[[0]
 [0]
 [0]]


### 3. Contanetated Jacobian Matrix

In [10]:
JM1 = np.concatenate ((J1,J2,J3),1)
#print(JM1)

JM2 = np.concatenate ((J4,J5,J6),1)
#print(JM2)

J = np.concatenate ((JM1,JM2),0)
print("J = ")
print(J)



J = 
[[ 1.71450552e-14  1.71450552e-14  0.00000000e+00]
 [ 1.10000000e+02  6.00000000e+01 -1.22464680e-16]
 [-0.00000000e+00 -0.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00]]
